#define _CRT_SECURE_NO_WARNINGS 1
#include <stdio.h>
#include <time.h>
#include <windows.h>
//void menu(int* input);
void Menu(int* input);
void Game(void);

int main(void)
{
	int input = 0;
	//随机数种子
	srand((unsigned int)time(NULL));
	printf("这是一个猜数字游戏。\n");
	do
	{
		Menu(&input);
		if (input != 0)
		{
			Game();
			printf("请问是否继续游戏？\n");
		}
	} while (input != 0);

	return 0;
}
//菜单
void Menu(int* input)
{
	do
	{
		printf("输入1进入游戏，输入0退出游戏。\n");
		printf("请选择是否进入游戏:");
		scanf("%d", input);
		//清空缓冲区
		if (getchar() != '\n')
			getchar();
		switch (*input)
		{
		case 1:
			printf("进入游戏。");
			system("cls");
			break;
		case 0:
			system("cls");
			printf("游戏退出。\n");
			break;
		default:
			printf("输入错误。\n");
		}
	} while ((*input) != 1 && (*input) != 0);
}

void Game(void)
{
	//生成一个数字 number generated by computer
	int n_c = rand()%100 + 1;
	//玩家输入的数字 number entered by player
	int n_p = 0;
	do
	{
		printf("请输入您猜测的数字：");
		scanf("%d", &n_p);
		//清空缓冲区
		if (getchar() != '\n')
			getchar();
		if (n_p > n_c)
			printf("猜大了\n");
		else if (n_p < n_c)
			printf("猜小了\n");
	} while (n_p != n_c);
	printf("正确！\n");
}